### ISSUE TITLE
为什么不写中文的readme

### ISSUE THREAD

**Issue by farmercode** [tencent-php/tsf#27]
难道这是个美帝写的吗？为什么readme的文档不是中文的？
作为天朝人，感觉第一文档还是应该写中文的好吧，先解决国内，然后才是走向世界吧！

**Comment by nxtreaming** [comment]
Shut up.

**Comment by farmercode** [comment]
楼上那SB是真美帝吗？ 还装上了
@nxtreaming

**Comment by Ir1d** [comment]
写全英文项目很正常的

**Comment by farmercode** [comment]
写全英文项目我觉得没有问题，但是我就是希望作为一个中国人，写中文文档可以帮助一些英文水平比较低的国内朋友。作为一个从小到大都是写方块字的人，鸟语你都写了，写一份自己的母语的文档也没啥问题吧！很多想入门编程的朋友有时候觉得自己领域中文资料不够，我还是觉得能帮助一点还是一点！对于2楼这种，呵呵！

**Comment by gaomd** [comment]
@farmercode 开口闭口「天朝」、「鸟语」的，呵呵。 

建议管理员 close 加 lock 此 issue（中文混「鸟语」，畅快）。

**Comment by farmercode** [comment]
@gaomd 高的自己是老外似的，不想做中国人和你爸说一下啊，说去找一个美国老爸！也不用再说中文了吧！可以开开心心用你的鸟文，如果我还喷你，那我就是狗！

**Comment by gaomd** [comment]
@farmercode 你先把中文写对再来喷吧，另外嘴巴擦干净点，你妈妈会感激你的。

![screen-shot-2016-03-06-at-00 35 04](https://cloud.githubusercontent.com/assets/113737/13548801/8ddb42ba-e333-11e5-8063-74bc84e4b0aa.png)

**Comment by farmercode** [comment]
我最早讨论的是中文文档可以帮助不收鸟语不好的国内编程同学更好的入门。玛德，高的自己很牛B一样！还在这和我喷！我说的是实话，感觉我们天朝容不下你，你可以滚啊！中国最不缺的就是人！更不用说狗了！

**Comment by farmercode** [comment]
哎，我乐意，语文老师走的早，体育老师代课了！xx就是矫情，

**Comment by farmercode** [comment]
@gaomd 矫情

**Comment by nxtreaming** [comment]
> 我最早讨论的是中文文档可以帮助不收鸟语不好的国内编程同学更好的入门。玛德，高的自己很牛B一样！还在这和我喷！我说的是实话，感觉我们天朝容不下你，你可以滚啊！中国最不缺的就是人！更不用说狗了！

u r SB.

**Comment by farmercode** [comment]
@nxtreaming 就这么和你爹说话啊！ SB玩意！
