### ISSUE TITLE
How to use muticallTest

### ISSUE THREAD

**Issue by ecyuan** [tencent-php/tsf#6]
What's the complete example code about muticallTest()?
The code can not run in readme.md.

**Comment by winterswang** [comment]
can you describe the problem you have met  in detail?

**Comment by ecyuan** [comment]
re:Re: [tsf] How to use muticallTest (#6)
李积远
2015年7月7日 22:36
详情
<php
require 'tsf/lib/tsf.php';
this->muticallTest();
function muticallTest(){
$calls=new Swoole\Client\Multi();
ip, data, secondReq=new Swoole\Client\UDP(port, timeout);
firstReq,'first');             //first request
secondReq,'second');             //second request
return res);
?>
There nothing output.

—
Reply to this email direct
